// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/healthsync/AIAnalysis.tsx": () => import("../components/mockups/healthsync/AIAnalysis.tsx"),
  "./components/mockups/healthsync/Dashboard.tsx": () => import("../components/mockups/healthsync/Dashboard.tsx"),
  "./components/mockups/healthsync/HealthHistory.tsx": () => import("../components/mockups/healthsync/HealthHistory.tsx"),
  "./components/mockups/healthsync/Login.tsx": () => import("../components/mockups/healthsync/Login.tsx"),
  "./components/mockups/healthsync/Notifications.tsx": () => import("../components/mockups/healthsync/Notifications.tsx"),
  "./components/mockups/healthsync/Onboarding1.tsx": () => import("../components/mockups/healthsync/Onboarding1.tsx"),
  "./components/mockups/healthsync/Onboarding2.tsx": () => import("../components/mockups/healthsync/Onboarding2.tsx"),
  "./components/mockups/healthsync/Onboarding3.tsx": () => import("../components/mockups/healthsync/Onboarding3.tsx"),
  "./components/mockups/healthsync/Onboarding4.tsx": () => import("../components/mockups/healthsync/Onboarding4.tsx"),
  "./components/mockups/healthsync/Profile.tsx": () => import("../components/mockups/healthsync/Profile.tsx"),
  "./components/mockups/healthsync/ResetPassword.tsx": () => import("../components/mockups/healthsync/ResetPassword.tsx"),
  "./components/mockups/healthsync/ResetSuccess.tsx": () => import("../components/mockups/healthsync/ResetSuccess.tsx"),
  "./components/mockups/healthsync/Signup.tsx": () => import("../components/mockups/healthsync/Signup.tsx"),
  "./components/mockups/healthsync/SignupStep2.tsx": () => import("../components/mockups/healthsync/SignupStep2.tsx"),
  "./components/mockups/healthsync/Splash.tsx": () => import("../components/mockups/healthsync/Splash.tsx"),
  "./components/mockups/healthsync/VitalBP.tsx": () => import("../components/mockups/healthsync/VitalBP.tsx"),
  "./components/mockups/healthsync/VitalGlucose.tsx": () => import("../components/mockups/healthsync/VitalGlucose.tsx"),
  "./components/mockups/healthsync/VitalHeartRate.tsx": () => import("../components/mockups/healthsync/VitalHeartRate.tsx"),
  "./components/mockups/healthsync/VitalOxygen.tsx": () => import("../components/mockups/healthsync/VitalOxygen.tsx")
};
